apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprodb
  labels:
    app: vprodb
spec:
  selector:
    matchLabels:
      app: vprodb
  replicas: 1
  template:
    metadata:
      labels:
        app: vprodb
    spec:
      containers:
        - name: vprodb
          image: miro0o96/vprofiledb
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: vpro-db-data
          ports:
            - name: vprodb
              containerPort: 3306
          env:
            - name: MQSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: db-pass
      nodeSelector:
        zone: us-east-2a
      volumes:
        - name: vpro-db-data
          awsElasticBlockStore:
            volumeID: vol-0890976e60288a246
            fsType: ext4
      initContainers:
        - name: busybox
          image: busybox:latest
          args: ["rm", "rf", "/var/lib/mysql/lost+found"]
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: vpro-db-data

